format_version: 1.0
artifactservers:
    "example_product":
        - "104.130.162.166"
reposervers:
    production:
        ord:
            "example_product":
                - "http://104.130.162.166"
